export const subjects = [
  'Computer Science',
  'Mathematics',
  'Physics',
  'Chemistry',
  'Biology',
  'Electronics',
  'Electrical',
  'Mechanical',
  'Civil',
  'Chemical',
  'Biotechnology',
  'Economics',
  'Psychology',
  'Literature',
  'History',
  'Political Science',
  'Geography',
  'Philosophy',
  // Add more subjects as needed
];

export const institutions = [
  'Birla Institute of Technology Mesra (BIT Mesra)',
  'Birla Institute of Technology and Science Pilani (BITS Pilani)',
  'Indian Institute of Technology Bombay',
  'Indian Institute of Technology Delhi',
  'Indian Institute of Technology Madras',
  'Indian Institute of Technology Kanpur',
  'Indian Institute of Technology Kharagpur',
  'Indian Institute of Science Bangalore',
  'Delhi University',
  'Mumbai University',
  'Anna University',
  'Jadavpur University',
  'University of Calcutta',
  'University of Delhi',
  'University of Mumbai',
  'xavier university',
  'christ university',
  'iiit bhubaneswar',
  'iiit hyderabad',
  'iiit lucknow',
  'iiit surat',
  'iiit bangalore';
  'iiit delhi',
  // Add more institutions as needed
]; 